In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Carregando o arquivo da análise

file = ('curitiba_apartment_real_estate_data.csv')
df = pd.read_csv(file)

In [5]:
df.head(20)

,usableAreas,totalAreas,suites,bathrooms,bedrooms,parkingSpaces,amenities,description,title,zipCode,lon,lat,street,neighborhood,poisList,yearlyIptu,monthlyCondoFee,price
0,77,90.0,1.0,2,3,1.0,"['BARBECUE_GRILL', 'ELEVATOR', 'GATED_COMMUNIT...","Apartamento com 3 dormitórios, sendo uma suíte...",Apartamento para venda tem 77 metros quadrados...,82540130,-49.249319,-25.394261,Rua Nossa Senhora de Nazaré,Boa Vista,"['BS:Estação Tubo Holanda', 'BS:Estação-tubo G...",700.0,400.0,595000
1,53,53.0,NaN,1,3,1.0,"['BARBECUE_GRILL', 'GATED_COMMUNITY', 'GYM', '...",Apartamento ensolarado e com linda vista pro P...,Apartamento ensolarado com 3 quartos ao lado d...,81320180,-49.326716,-25.474533,Rua Alfredo José Pinto,Fazendinha,"['BS:Rua José Gonçalves Júnior, 182', 'BS:Rua ...",NaN,392.0,185000
2,113,NaN,1.0,4,3,2.0,"['POOL', 'BARBECUE_GRILL', 'ELEVATOR', 'GATED_...","22º andar, face Norte, linda vista para a Serr...",Apt para venda no Cond. Botânica: 113 m² com 3...,80050470,-49.239110,-25.437162,Rua Coronel Pedro Scherer Sobrinho,Cristo Rei,"['BS:Estação Hospital Cajuru', 'BS:Linha Turis...",240.0,550.0,1220000
3,93,106.0,1.0,2,3,2.0,"['POOL', 'FURNISHED', 'BARBECUE_GRILL', 'ELEVA...",Apartamento Residencial com 70m2 interno total...,Apartamento Mobiliado de Porteira Fechada incl...,81210310,-49.335318,-25.442254,Rua Jeremias Maciel Perretto,Campo Comprido,"['BS:Estação-tubo Mossunguê', 'BS:Mossunguê', ...",400.0,600.0,610000
4,66,NaN,1.0,2,3,1.0,"['BARBECUE_GRILL', 'GATED_COMMUNITY', 'PETS_AL...",Excelente apto garden com 66m² de área útil em...,Apartamento Novo Mundo 66m² útil,81050150,-49.304465,-25.492857,Rua Deputado Waldemiro Pedroso,Novo Mundo,"['BS:Ponto - 672 Formosa', 'BS:Ponto - 615 Ube...",NaN,NaN,269990
5,57,70.0,NaN,1,3,1.0,"['GATED_COMMUNITY', 'PETS_ALLOWED', 'GARDEN', ...",Apartamento no Santa Quitéria. Direto com o pr...,Apartamento Impecável - totalmente reformado,80330180,-49.318869,-25.469658,Rua Rezala Simão,Santa Quitéria,"['BS:Rua José Gonçalves Júnior, 182', 'BS:Rua ...",400.0,500.0,230000
6,102,NaN,1.0,3,3,2.0,"['POOL', 'FURNISHED', 'BARBECUE_GRILL', 'ELEVA...",Lindo apartamento em região nobre Água Verde/B...,Apartamento para venda com 102 metros quadrado...,80240031,-49.289398,-25.449608,Avenida Iguaçu,Água Verde,"['BS:Estacao Silva Jardim', 'BS:Estação Silva ...",198.0,1000.0,650000
7,88,146.0,1.0,2,3,1.0,"['BARBECUE_GRILL', 'ELEVATOR', 'PLAYGROUND', '...","Apartamento impecável, direto com o proprietár...",Apartamento para venda possui 88 metros quadra...,82510000,-49.244942,-25.398545,Avenida Paraná,Bacacheri,"['BS:Estação Tubo Holanda', 'BS:Estação-tubo G...",1000.0,800.0,495000
8,57,70.0,NaN,2,2,1.0,"['BARBECUE_GRILL', 'ELEVATOR', 'GATED_COMMUNIT...",Excelente apartamento mobiliado na melhor regi...,Apartamento para venda com 57 metros quadrados...,80730000,-49.298311,-25.432810,Rua Padre Anchieta,Bigorrilho,"['BS:Estação-tubo Bigorrilho', 'BS:Estação-tub...",400.0,450.0,345000
9,80,140.0,1.0,2,2,2.0,"['FURNISHED', 'BARBECUE_GRILL', 'ELEVATOR', 'P...","Apartamento recém reformado, decorado, ensolar...",Apartamento para venda com 80 metros quadrados...,80510360,-49.286421,-25.420442,Rua Raquel Prado,Mercês,"['BS:Av. Manoel Ribas, 200', 'BS:Praça da Band...",NaN,335.0,699900
10,38,46.0,NaN,1,2,1.0,"['BARBECUE_GRILL', 'PETS_ALLOWED', 'PLAYGROUND...",O endereço do anúncio está errado. Erramos na ...,"Apartamento para venda, tem 38 metros quadrado...",80330000,-49.299102,-25.471781,Rua Carlos Dietzsch,Portão,"['BS:180833', 'BS:180105', 'BS:R. João Bettega...",NaN,250.0,126000
11,126,NaN,3.0,5,3,2.0,"['POOL', 'FURNISHED', 'BARBECUE_GRILL', 'ELEVA...","Condomínio The Square. Apartamento face norte,...",Apartamento para venda possui 126 metros quadr...,80320200,-49.295274,-25.468606,Rua Professora Doracy Cezzarino,Portão,"['BS:Estacao Morretes', 'BS:180833', 'BS:18010...",NaN,800.0,1350000
12,76,95.0,NaN,2,3,1.0,"['PETS_ALLOWED', 'GARDEN', 'PLAYGROUND', 'ELEC...",Excelente Apartamento Face Leste Reformado com...,Excelente Apartamento face leste Totalmente Re...,80050350,-49.244471,-25.435539,Avenida São José,Cristo Rei,"['BS:Estação Hospital Cajuru', 'BS:Estação-tub...",715.0,350.0,345000
13,168,NaN,1.0,3,4,2.0,"['POOL', 'FURNISHED', 'ELEVATOR', 'PETS_ALLOWE...","Apartamento bem localizado, super ensolarado, ...",Apartamento ensolarado e bem localizado,80410030,-49.282143,-25.425858,Rua Padre Anchieta,São Francisco,"['BS:Av. Manoel Ribas, 200', 'BS:Estação Praça...",1400.0,1300.0,720000
14,59,NaN,NaN,1,3,1.0,"['BARBECUE_GRILL', 'GATED_COMMUNITY', 'GYM', '...","Unidade exclusiva de revenda, melhor custo-ben...",Apartamento a venda com 3 quartos e vaga de ga...,80330180,-49.318889,-25.467083,Rua Rezala Simão,Santa Quitéria,"['BS:Rua José Gonçalves Júnior, 182', 'BS:Rua ...",NaN,300.0,230000
15,213,186.0,1.0,2,3,1.0,"['FURNISHED', 'ELEVATOR', 'PETS_ALLOWED', 'AIR...",Belíssimo apartamento de alto padrão recém ref...,Belíssimo Apartamento Reformado à venda - 213 ...,80010090,NaN,NaN,NaN,Centro,"['BS:Praça Rui Barbosa (607)', 'BS:Praça Rui B...",3100.0,1400.0,1195000
16,78,130.0,1.0,2,3,2.0,"['POOL', 'FURNISHED', 'BARBECUE_GRILL', 'ELEVA...",Excelente apartamento no 19º (Último andar) do...,Apartamento para venda com 78 metros quadrados...,81130020,-49.296779,-25.499005,Rua José Clementino Bettega,Capão Raso,"['BS:Estação-tubo José Bettega', 'BS:Estação S...",980.0,700.0,649900
17,105,NaN,1.0,2,3,1.0,"['ELEVATOR', 'GATED_COMMUNITY', 'GYM', 'PLAYGR...",O apartamento no bairro Água Verde tem 105 met...,Apartamento para venda com 105 metros quadrado...,80620130,-49.278776,-25.460558,Rua Dom Pedro I,Água Verde,"['BS:Praça Bento M. da Rocha Neto', 'BS:Largo ...",783.0,437.0,580000
18,78,NaN,1.0,2,2,2.0,"['FURNISHED', 'BARBECUE_GRILL', 'ELEVATOR', 'G...","Apto. em área nobre de Curitiba, seminovo (2 a...",Apartamento para venda com 78 metros quadrados...,80320240,-49.292953,-25.461823,Rua Guaianazes,Vila Izabel,"['BS:Estação Sebastião Paraná', 'BS:Estação Tu...",1000.0,400.0,580000
19,70,NaN,NaN,1,2,1.0,"['PETS_ALLOWED', 'FURNISHED', 'ELECTRONIC_GATE...","Prático, Conveniente e Moderno no ❤️ de Curiti...",Apartamento Mobiliado Venda Cristo Rei | 70 m²...,80050360,-49.243818,-25.435913,Rua Poeta Francisco Ferreira Leite,Cristo Rei,"['BS:Estação Hospital Cajuru', 'BS:Estação-tub...",NaN,430.0,295000

In [8]:
df.shape

(18760, 18)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18760 entries, 0 to 18759
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   usableAreas      18760 non-null  int64
 1   totalAreas       18030 non-null  float64
 2   suites           17456 non-null  float64
 3   bathrooms        18760 non-null  int64
 4   bedrooms         18760 non-null  int64
 5   parkingSpaces    18097 non-null  float64
 6   amenities        18760 non-null  object
 7   description      18730 non-null  object
 8   title            18633 non-null  object
 9   zipCode          18760 non-null  int64
 10  lon              13195 non-null  float64
 11  lat              13195 non-null  float64
 12  street           15689 non-null  object
 13  neighborhood     18760 non-null  object
 14  poisList         18760 non-null  object
 15  yearlyIptu       14412 non-null  float64
 16  monthlyCondoFee  15169 non-null  float64
 17  price            18760 non-null  int64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.6+ MB

In [13]:
df.describe().round(2)

,usableAreas,totalAreas,suites,bathrooms,bedrooms,parkingSpaces,zipCode,lon,lat,yearlyIptu,monthlyCondoFee,price
count,18760.00,18030.00,17456.00,18760.00,18760.00,18097.00,18760.00,13195.00,13195.00,14412.00,15169.00,1.876000e+04
mean,111.94,204.34,1.23,2.39,2.50,1.58,80636130.80,-49.28,-25.44,3085.85,4179.38,1.099262e+06
std,101.24,2018.78,1.05,1.38,0.88,1.16,646291.29,0.06,0.05,154096.02,160874.76,1.840035e+06
min,10.00,1.00,0.00,1.00,1.00,0.00,80010000.00,-54.58,-25.59,0.00,0.00,8.500000e+02
25%,57.00,69.00,1.00,1.00,2.00,1.00,80240020.00,-49.29,-25.46,0.00,0.00,3.500000e+05
50%,89.00,119.00,1.00,2.00,3.00,1.00,80530010.00,-49.28,-25.44,0.00,380.00,6.500000e+05
75%,139.00,199.00,2.00,3.00,3.00,2.00,80730320.00,-49.26,-25.43,150.00,730.00,1.267950e+06
max,5000.00,174932.00,8.00,11.00,8.00,40.00,97010491.00,-49.18,-20.43,15033530.00,16000000.00,1.290331e+08

In [19]:
df['Valor_por_m2'] = df['price'] / df['usableAreas']

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18760 entries, 0 to 18759
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   usableAreas      18760 non-null  int64
 1   totalAreas       18030 non-null  float64
 2   suites           17456 non-null  float64
 3   bathrooms        18760 non-null  int64
 4   bedrooms         18760 non-null  int64
 5   parkingSpaces    18097 non-null  float64
 6   amenities        18760 non-null  object
 7   description      18730 non-null  object
 8   title            18633 non-null  object
 9   zipCode          18760 non-null  int64
 10  lon              13195 non-null  float64
 11  lat              13195 non-null  float64
 12  street           15689 non-null  object
 13  neighborhood     18760 non-null  object
 14  poisList         18760 non-null  object
 15  yearlyIptu       14412 non-null  float64
 16  monthlyCondoFee  15169 non-null  float64
 17  price            18760 non-null  int64
 18  Valor_por_m2     18760 non-null  float64
dtypes: float64(8), int64(5), object(6)
memory usage: 2.7+ MB

In [32]:
#Excluir todas linhas de valores nulos seria muito radical pois o dataframe ficaria com metade das linhas, em relação ao original.
df.dropna()

,usableAreas,totalAreas,suites,bathrooms,bedrooms,parkingSpaces,amenities,description,title,zipCode,lon,lat,street,neighborhood,poisList,yearlyIptu,monthlyCondoFee,price,Valor_por_m2
0,77,90.0,1.0,2,3,1.0,"['BARBECUE_GRILL', 'ELEVATOR', 'GATED_COMMUNIT...","Apartamento com 3 dormitórios, sendo uma suíte...",Apartamento para venda tem 77 metros quadrados...,82540130,-49.249319,-25.394261,Rua Nossa Senhora de Nazaré,Boa Vista,"['BS:Estação Tubo Holanda', 'BS:Estação-tubo G...",700.0,400.0,595000,7727.272727
3,93,106.0,1.0,2,3,2.0,"['POOL', 'FURNISHED', 'BARBECUE_GRILL', 'ELEVA...",Apartamento Residencial com 70m2 interno total...,Apartamento Mobiliado de Porteira Fechada incl...,81210310,-49.335318,-25.442254,Rua Jeremias Maciel Perretto,Campo Comprido,"['BS:Estação-tubo Mossunguê', 'BS:Mossunguê', ...",400.0,600.0,610000,6559.139785
7,88,146.0,1.0,2,3,1.0,"['BARBECUE_GRILL', 'ELEVATOR', 'PLAYGROUND', '...","Apartamento impecável, direto com o proprietár...",Apartamento para venda possui 88 metros quadra...,82510000,-49.244942,-25.398545,Avenida Paraná,Bacacheri,"['BS:Estação Tubo Holanda', 'BS:Estação-tubo G...",1000.0,800.0,495000,5625.000000
16,78,130.0,1.0,2,3,2.0,"['POOL', 'FURNISHED', 'BARBECUE_GRILL', 'ELEVA...",Excelente apartamento no 19º (Último andar) do...,Apartamento para venda com 78 metros quadrados...,81130020,-49.296779,-25.499005,Rua José Clementino Bettega,Capão Raso,"['BS:Estação-tubo José Bettega', 'BS:Estação S...",980.0,700.0,649900,8332.051282
23,94,168.0,1.0,2,3,2.0,"['FURNISHED', 'BARBECUE_GRILL', 'ELEVATOR', 'G...","Apartamento 3Q mobiliado, pronto para morar, n...",Apartamento para venda possui 94 metros quadra...,80620230,-49.284776,-25.459128,Rua Monsenhor Manoel Vicente,Água Verde,"['BS:Largo Ciro Silva', 'BS:Estação tubo Dom P...",100.0,530.0,680000,7234.042553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18728,126,240.0,2.0,2,2,2.0,"['POOL', 'BARBECUE_GRILL', 'ELEVATOR', 'BALCON...",CASA MILANO LANÇAMENTO<br>Empreendimento de al...,Apartamento - Bigorrilho - Curitiba/PR,80730030,-49.304550,-25.436016,Rua Martim Afonso,Bigorrilho,"['BS:Estação-tubo Gastão Câmara', 'BS:Estação-...",0.0,0.0,1300000,10317.460317
18741,132,10.0,1.0,3,3,1.0,[],"Apartamento à Venda, 132m² por R$ 499.500. Big...","Apartamento à venda 3 Quartos, 1 Suite, 1 Vaga...",80730440,-49.291627,-25.431297,Avenida Cândido Hartmann,Mercês,"['BS:Estação-tubo Praça da Ucrânia', 'BS:Estaç...",140.0,375.0,499500,3784.090909
18742,132,10.0,1.0,3,3,1.0,[],"Apartamento à Venda, 132m² por R$ 499.500. Big...","Apartamento à venda 3 Quartos, 1 Suite, 1 Vaga...",80730440,-49.291627,-25.431297,Avenida Cândido Hartmann,Mercês,"['BS:Estação-tubo Praça da Ucrânia', 'BS:Estaç...",140.0,375.0,499500,3784.090909
18751,274,375.0,2.0,3,4,2.0,"['KITCHEN', 'BARBECUE_GRILL']","Apartamento Duplex à Venda, 274m² por R$ 1.100...",Apartamento Duplex à venda 4 quartos 2 suítes ...,80730030,-49.291830,-25.431390,Rua Martim Afonso,Bigorrilho,"['BS:Estação-tubo Praça da Ucrânia', 'BS:Estaç...",190.0,1644.0,1100000,4014.598540
18758,372,700.0,4.0,6,4,5.0,['POOL'],"O Vigo, é um empreendimento longe do comum, do...",APARTAMENTO com 4 dormitórios à venda com 700....,80730180,-49.289262,-25.435242,Rua Saldanha Marinho,Bigorrilho,"['BS:Estação-tubo Praça da Ucrânia', 'BS:Estaç...",0.0,0.0,5901000,15862.903226

In [ ]:
#TRATAMENTOS INICIAIS

#totalAreas = excluir
#suites= colocar 0 -> fillna
#parkingSpaces colocar 0 -> fillna
#description e title = excluir
#zipcode trocar o tipo para object -> astype e tentar formatar ela para XXXXX-XXX
#street = "sem endereço" -> fillna
#yearlyIptu = 0 -> fillna
#monthlyCondoFee = 0 -> fillna
#price no formato de milhares XXX.XXX
#Valor_por_m2 no formato XXXXX.XX

#Renomear TODAS as colunas para português

In [48]:
# criar um grafico pizza, a soma do restante ser representada como outros
df.neighborhood.value_counts(1)[0:10]*100

Água Verde           20.719616
Centro               15.623667
Bigorrilho           12.132196
Batel                 7.771855
Rebouças              4.371002
Cabral                3.219616
Portão                3.027719
Vila Izabel           2.915778
Cidade Industrial     2.452026
Cristo Rei            2.153518
Name: neighborhood, dtype: float64